"""baseline schema: users, categories, products, orders, order_items

Revision ID: 69cd99b04162
Revises: 
Create Date: 2026-08-15 12:10:21.066113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69cd99b04162'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # NOTE: this file was auto-generated by `flask db migrate`, but the
    # autogenerate diff also picked up cosmetic differences between the
    # SQLAlchemy models and the Checkpoint 1 schema.sql DDL (indexes,
    # CHECK constraints, FK ondelete clauses declared with raw SQL rather
    # than in the ORM). Those are NOT real schema changes and dropping them
    # would silently weaken the existing schema, so they were removed from
    # this migration by hand. This baseline migration only records the one
    # genuinely new column for Checkpoint 2: `users.username`.
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint('uq_users_username', ['username'])


def downgrade():
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_username', type_='unique')
        batch_op.drop_column('username')
